import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/demos/breadcrumb/lateral')({
  beforeLoad: ({ context }) => beforeLoadAdminPage('/demos/breadcrumb/lateral', context.user),
  staticData: { adminPagePath: '/demos/breadcrumb/lateral' },
})
