import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/demos/features/menu-query')({
  beforeLoad: ({ context }) => beforeLoadAdminPage('/demos/features/menu-query', context.user),
  staticData: { adminPagePath: '/demos/features/menu-query' },
})
