import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/examples/motion')({
  beforeLoad: ({ context }) => beforeLoadAdminPage('/examples/motion', context.user),
  staticData: { adminPagePath: '/examples/motion' },
})
