import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'
import { analyticsQueryOptions } from '~/features/dashboard/analytics/queries'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/dashboard/analytics')({
  beforeLoad: ({ context }) => beforeLoadAdminPage('/dashboard/analytics', context.user),
  loader: ({ context }) => context.queryClient.ensureQueryData(analyticsQueryOptions),
  staticData: { adminPagePath: '/dashboard/analytics' },
})
