import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/system/role')({
  beforeLoad: ({ context }) => beforeLoadAdminPage('/system/role', context.user),
  staticData: { adminPagePath: '/system/role' },
})
