import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/demos/outside/iframe/react-document')({
  beforeLoad: ({ context }) =>
    beforeLoadAdminPage('/demos/outside/iframe/react-document', context.user),
  staticData: { adminPagePath: '/demos/outside/iframe/react-document' },
})
