import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/dashboard/workspace')({
  beforeLoad: ({ context }) => beforeLoadAdminPage('/dashboard/workspace', context.user),
  staticData: { adminPagePath: '/dashboard/workspace' },
})
