import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/examples/form/rules')({
  beforeLoad: ({ context }) => beforeLoadAdminPage('/examples/form/rules', context.user),
  staticData: { adminPagePath: '/examples/form/rules' },
})
