import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/demos/features/login-expired')({
  beforeLoad: ({ context }) => beforeLoadAdminPage('/demos/features/login-expired', context.user),
  staticData: { adminPagePath: '/demos/features/login-expired' },
})
