import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/examples/captcha/point-selection')({
  beforeLoad: ({ context }) =>
    beforeLoadAdminPage('/examples/captcha/point-selection', context.user),
  staticData: { adminPagePath: '/examples/captcha/point-selection' },
})
