import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/system/dept')({
  beforeLoad: ({ context }) => beforeLoadAdminPage('/system/dept', context.user),
  staticData: { adminPagePath: '/system/dept' },
})
