import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/demos/nested/menu3/menu3-1')({
  beforeLoad: ({ context }) => beforeLoadAdminPage('/demos/nested/menu3/menu3-1', context.user),
  staticData: { adminPagePath: '/demos/nested/menu3/menu3-1' },
})
