import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/demos/fallback/offline')({
  beforeLoad: ({ context }) => beforeLoadAdminPage('/demos/fallback/offline', context.user),
  staticData: { adminPagePath: '/demos/fallback/offline' },
})
