import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/examples/form/scroll-to-error-test')({
  beforeLoad: ({ context }) =>
    beforeLoadAdminPage('/examples/form/scroll-to-error-test', context.user),
  staticData: { adminPagePath: '/examples/form/scroll-to-error-test' },
})
