import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/demos/features/hide-menu-children')({
  beforeLoad: ({ context }) =>
    beforeLoadAdminPage('/demos/features/hide-menu-children', context.user),
  staticData: { adminPagePath: '/demos/features/hide-menu-children' },
})
