import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/demos/features/detail/$id')({
  beforeLoad: ({ context }) => beforeLoadAdminPage('/demos/features/detail/:id', context.user),
  staticData: { adminPagePath: '/demos/features/detail/:id' },
})
