import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/examples/ellipsis')({
  beforeLoad: ({ context }) => beforeLoadAdminPage('/examples/ellipsis', context.user),
  staticData: { adminPagePath: '/examples/ellipsis' },
})
