import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/system/menu')({
  beforeLoad: ({ context }) => beforeLoadAdminPage('/system/menu', context.user),
  staticData: { adminPagePath: '/system/menu' },
})
