import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/demos/badge/color')({
  beforeLoad: ({ context }) => beforeLoadAdminPage('/demos/badge/color', context.user),
  staticData: { adminPagePath: '/demos/badge/color' },
})
