import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/examples/tippy')({
  beforeLoad: ({ context }) => beforeLoadAdminPage('/examples/tippy', context.user),
  staticData: { adminPagePath: '/examples/tippy' },
})
