import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/form-array-demo')({
  beforeLoad: ({ context }) => beforeLoadAdminPage('/form-array-demo', context.user),
  staticData: { adminPagePath: '/form-array-demo' },
})
