import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/examples/context-menu')({
  beforeLoad: ({ context }) => beforeLoadAdminPage('/examples/context-menu', context.user),
  staticData: { adminPagePath: '/examples/context-menu' },
})
