import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/demos/access/menu-visible-403')({
  beforeLoad: ({ context }) => beforeLoadAdminPage('/demos/access/menu-visible-403', context.user),
  staticData: { adminPagePath: '/demos/access/menu-visible-403' },
})
