import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/demos/access/page-control')({
  beforeLoad: ({ context }) => beforeLoadAdminPage('/demos/access/page-control', context.user),
  staticData: { adminPagePath: '/demos/access/page-control' },
})
