import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/fallback/500')({
  beforeLoad: ({ context }) => beforeLoadAdminPage('/fallback/500', context.user),
  staticData: { adminPagePath: '/fallback/500' },
})
