import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/examples/pro-table/basic')({
  beforeLoad: ({ context }) => beforeLoadAdminPage('/examples/pro-table/basic', context.user),
  staticData: { adminPagePath: '/examples/pro-table/basic' },
})
