import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/examples/json-viewer')({
  beforeLoad: ({ context }) => beforeLoadAdminPage('/examples/json-viewer', context.user),
  staticData: { adminPagePath: '/examples/json-viewer' },
})
