import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/demos/features/preferences-extension')({
  beforeLoad: ({ context }) =>
    beforeLoadAdminPage('/demos/features/preferences-extension', context.user),
  staticData: { adminPagePath: '/demos/features/preferences-extension' },
})
