import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/examples/layout/col-page')({
  beforeLoad: ({ context }) => beforeLoadAdminPage('/examples/layout/col-page', context.user),
  staticData: { adminPagePath: '/examples/layout/col-page' },
})
