import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/demos/features/request-params-serializer')({
  beforeLoad: ({ context }) =>
    beforeLoadAdminPage('/demos/features/request-params-serializer', context.user),
  staticData: { adminPagePath: '/demos/features/request-params-serializer' },
})
