import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/examples/drawer')({
  beforeLoad: ({ context }) => beforeLoadAdminPage('/examples/drawer', context.user),
  staticData: { adminPagePath: '/examples/drawer' },
})
