import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/demos/features/icons')({
  beforeLoad: ({ context }) => beforeLoadAdminPage('/demos/features/icons', context.user),
  staticData: { adminPagePath: '/demos/features/icons' },
})
