import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/demos/active-icon/children')({
  beforeLoad: ({ context }) => beforeLoadAdminPage('/demos/active-icon/children', context.user),
  staticData: { adminPagePath: '/demos/active-icon/children' },
})
