import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/system/user')({
  beforeLoad: ({ context }) => beforeLoadAdminPage('/system/user', context.user),
  staticData: { adminPagePath: '/system/user' },
})
