import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/examples/count-to')({
  beforeLoad: ({ context }) => beforeLoadAdminPage('/examples/count-to', context.user),
  staticData: { adminPagePath: '/examples/count-to' },
})
