import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/demos/outside/external-link/react')({
  beforeLoad: ({ context }) =>
    beforeLoadAdminPage('/demos/outside/external-link/react', context.user),
  staticData: { adminPagePath: '/demos/outside/external-link/react' },
})
