import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/examples/form/label-width')({
  beforeLoad: ({ context }) => beforeLoadAdminPage('/examples/form/label-width', context.user),
  staticData: { adminPagePath: '/examples/form/label-width' },
})
