import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/fallback/coming-soon')({
  beforeLoad: ({ context }) => beforeLoadAdminPage('/fallback/coming-soon', context.user),
  staticData: { adminPagePath: '/fallback/coming-soon' },
})
