import { createFileRoute } from '@tanstack/react-router'

import { beforeLoadAdminPage } from '~/core/admin-route'

// Generated by scripts/generate-admin-routes.mjs.
export const Route = createFileRoute('/_app/demos/nested/menu1')({
  beforeLoad: ({ context }) => beforeLoadAdminPage('/demos/nested/menu1', context.user),
  staticData: { adminPagePath: '/demos/nested/menu1' },
})
