import { z } from 'zod'

export const widgetKeys = [
  'globalSearch',
  'preferences',
  'themeToggle',
  'languageToggle',
  'timezone',
  'fullscreen',
  'refresh',
  'notification',
  'lockScreenBtn',
  'logoutBtn',
] as const

export const widgetKeySchema = z.enum(widgetKeys)
export type WidgetKey = z.infer<typeof widgetKeySchema>

export const widgetPositionSchema = z.enum(['header', 'none', 'user-dropdown'])
export const preferencesButtonPositionSchema = z.enum([
  'auto',
  'fixed',
  'header',
  'none',
  'user-dropdown',
])

export const preferencesSchema = z.object({
  accessMode: z.enum(['backend', 'frontend']).default('frontend'),
  animations: z.boolean(),
  authPageLayout: z.enum(['panel-center', 'panel-left', 'panel-right']),
  breadcrumbHideOnlyOne: z.boolean(),
  breadcrumbStyle: z.enum(['background', 'normal']),
  colorGrayMode: z.boolean(),
  colorMode: z.enum(['dark', 'light', 'system']),
  colorPrimary: z.string().regex(/^#[\da-f]{6}$/i),
  colorWeakMode: z.boolean(),
  compact: z.boolean(),
  contentCompact: z.enum(['compact', 'wide']),
  copyrightCompanyName: z.string(),
  copyrightCompanySiteLink: z.string(),
  copyrightDate: z.string(),
  copyrightEnable: z.boolean(),
  copyrightIcp: z.string(),
  copyrightIcpLink: z.string(),
  dynamicTitle: z.boolean(),
  enableCheckUpdates: z.boolean(),
  enableCopyPreferences: z.boolean(),
  enableStickyPreferencesNavigationBar: z.boolean(),
  fontSize: z.number().min(12).max(20),
  footerFixed: z.boolean(),
  headerEnable: z.boolean(),
  headerMenuAlign: z.enum(['center', 'end', 'start']),
  headerMode: z.enum(['auto', 'auto-scroll', 'fixed', 'static']),
  locale: z.enum(['en-US', 'zh-CN', 'zh-TW']),
  navigationAccordion: z.boolean(),
  navigationMode: z.enum([
    'full-content',
    'header-mixed-nav',
    'header-nav',
    'header-sidebar-nav',
    'mixed-nav',
    'sidebar-mixed-nav',
    'sidebar-nav',
  ]),
  navigationSplit: z.boolean(),
  navigationStyle: z.enum(['plain', 'rounded']),
  showcaseDefaultVisibleRows: z.number().int().min(1).max(8).default(4),
  showcaseEnableQuickActions: z.boolean().default(true),
  showcaseHighlightTone: z.enum(['default', 'success', 'warning']).default('default'),
  showcaseReportTitle: z.string().default(''),
  preferencesButtonPosition: preferencesButtonPositionSchema,
  radius: z.number().min(0).max(16),
  shortcutKeysEnable: z.boolean(),
  shortcutKeysEscape: z.boolean(),
  shortcutKeysLockScreen: z.boolean(),
  shortcutKeysLogout: z.boolean(),
  shortcutKeysSearch: z.boolean(),
  semiDarkHeader: z.boolean(),
  semiDarkSidebar: z.boolean(),
  semiDarkSidebarSub: z.boolean(),
  sidebarAutoActivateChild: z.boolean(),
  sidebarCollapsed: z.boolean(),
  sidebarCollapsedButton: z.boolean(),
  sidebarCollapsedShowTitle: z.boolean(),
  sidebarDraggable: z.boolean(),
  sidebarEnable: z.boolean(),
  sidebarFixedButton: z.boolean(),
  sidebarWidth: z.number().min(180).max(320),
  showBreadcrumb: z.boolean(),
  showBreadcrumbHome: z.boolean(),
  showBreadcrumbIcon: z.boolean(),
  showFooter: z.boolean(),
  showFullscreen: z.boolean(),
  showGlobalSearch: z.boolean(),
  showLanguageToggle: z.boolean(),
  showLockScreen: z.boolean(),
  showNotification: z.boolean(),
  showRefresh: z.boolean(),
  showTabs: z.boolean(),
  showTabIcons: z.boolean(),
  showTabMaximize: z.boolean(),
  showTabMore: z.boolean(),
  showThemeToggle: z.boolean(),
  showTimezone: z.boolean(),
  showWatermark: z.boolean(),
  tabDraggable: z.boolean(),
  tabMaxCount: z.number().int().min(0).max(30),
  tabMiddleClickToClose: z.boolean(),
  tabPersist: z.boolean(),
  tabStyle: z.enum(['brisk', 'card', 'chrome', 'plain']),
  tabVisitHistory: z.boolean(),
  tabWheelable: z.boolean(),
  timezone: z.string().min(1),
  transitionLoading: z.boolean(),
  transitionName: z.enum(['fade', 'fade-down', 'fade-slide', 'fade-up']),
  transitionProgress: z.boolean(),
  watermarkContent: z.string(),
  widgetFullscreenPosition: widgetPositionSchema,
  widgetGlobalSearchPosition: widgetPositionSchema,
  widgetLanguagePosition: widgetPositionSchema,
  widgetLockScreenPosition: widgetPositionSchema,
  widgetLogoutPosition: widgetPositionSchema,
  widgetNotificationPosition: widgetPositionSchema,
  widgetOrder: z.array(widgetKeySchema).transform((keys) => [...new Set([...keys, ...widgetKeys])]),
  widgetRefreshPosition: widgetPositionSchema,
  widgetThemePosition: widgetPositionSchema,
  widgetTimezonePosition: widgetPositionSchema,
})

export type AppPreferences = z.infer<typeof preferencesSchema>

const legacyHeaderWidgetPositions = {
  widgetFullscreenPosition: 'user-dropdown',
  widgetLanguagePosition: 'user-dropdown',
  widgetRefreshPosition: 'user-dropdown',
  widgetTimezonePosition: 'user-dropdown',
} as const

export const defaultPreferences = {
  accessMode: 'frontend',
  animations: true,
  authPageLayout: 'panel-right',
  breadcrumbHideOnlyOne: false,
  breadcrumbStyle: 'normal',
  colorGrayMode: false,
  colorMode: 'light',
  colorPrimary: '#006fe6',
  colorWeakMode: false,
  compact: false,
  contentCompact: 'wide',
  copyrightCompanyName: 'Qing React Admin',
  copyrightCompanySiteLink: 'https://react.dev',
  copyrightDate: '2026',
  copyrightEnable: false,
  copyrightIcp: '',
  copyrightIcpLink: '',
  dynamicTitle: true,
  enableCheckUpdates: true,
  enableCopyPreferences: true,
  enableStickyPreferencesNavigationBar: true,
  fontSize: 14,
  footerFixed: false,
  headerEnable: true,
  headerMenuAlign: 'start',
  headerMode: 'fixed',
  locale: 'zh-CN',
  navigationAccordion: true,
  navigationMode: 'sidebar-nav',
  navigationSplit: true,
  navigationStyle: 'rounded',
  showcaseDefaultVisibleRows: 4,
  showcaseEnableQuickActions: true,
  showcaseHighlightTone: 'default',
  showcaseReportTitle: '',
  preferencesButtonPosition: 'auto',
  radius: 8,
  shortcutKeysEnable: true,
  shortcutKeysEscape: false,
  shortcutKeysLockScreen: true,
  shortcutKeysLogout: true,
  shortcutKeysSearch: true,
  semiDarkHeader: false,
  semiDarkSidebar: false,
  semiDarkSidebarSub: false,
  sidebarAutoActivateChild: false,
  sidebarCollapsed: false,
  sidebarCollapsedButton: true,
  sidebarCollapsedShowTitle: false,
  sidebarDraggable: true,
  sidebarEnable: true,
  sidebarFixedButton: true,
  sidebarWidth: 216,
  showBreadcrumb: true,
  showBreadcrumbHome: false,
  showBreadcrumbIcon: false,
  showFooter: false,
  showFullscreen: true,
  showGlobalSearch: true,
  showLanguageToggle: true,
  showLockScreen: true,
  showNotification: true,
  showRefresh: false,
  showTabs: true,
  showTabIcons: false,
  showTabMaximize: false,
  showTabMore: true,
  showThemeToggle: true,
  showTimezone: true,
  showWatermark: false,
  tabDraggable: true,
  tabMaxCount: 12,
  tabMiddleClickToClose: false,
  tabPersist: true,
  tabStyle: 'plain',
  tabVisitHistory: true,
  tabWheelable: true,
  timezone: 'Asia/Shanghai',
  transitionLoading: true,
  transitionName: 'fade-slide',
  transitionProgress: true,
  watermarkContent: '',
  widgetFullscreenPosition: 'header',
  widgetGlobalSearchPosition: 'header',
  widgetLanguagePosition: 'header',
  widgetLockScreenPosition: 'user-dropdown',
  widgetLogoutPosition: 'user-dropdown',
  widgetNotificationPosition: 'header',
  widgetOrder: [...widgetKeys],
  widgetRefreshPosition: 'none',
  widgetThemePosition: 'header',
  widgetTimezonePosition: 'header',
} satisfies AppPreferences

export function parsePreferences(candidate: unknown): AppPreferences {
  const storedResult = z.record(z.string(), z.unknown()).safeParse(candidate)
  const stored = storedResult.success ? storedResult.data : {}
  const hasLegacyHeaderWidgetDefaults = Object.entries(legacyHeaderWidgetPositions).every(
    ([key, value]) => stored[key] === value,
  )
  const migrated = hasLegacyHeaderWidgetDefaults
    ? {
        ...stored,
        widgetFullscreenPosition: 'header',
        widgetLanguagePosition: 'header',
        widgetRefreshPosition: 'none',
        widgetTimezonePosition: 'header',
      }
    : stored
  const result = preferencesSchema.safeParse({ ...defaultPreferences, ...migrated })
  return result.success ? result.data : defaultPreferences
}
